# see: https://docs.cilium.io/en/stable/installation/cni-chaining-aws-cni/#chaining-aws-cni
cilium:
  cni:
    chainingMode: aws-cni
    exclusive: false
  # as ENI IP addresses can be routed directly in the VPC, we can disable masquerade and tunnel
  enableIPv4Masquerade: false
  tunnel: disabled
  endpointRoutes:
    enabled: true
  routingMode: native 

  # enable hubble
  hubble:
    relay:
      enabled: true
    ui:
      enabled: true

  # k8s ingress support
  nodePort:
    enabled: true
  kubeProxyReplacement: true
  k8sServiceHost: F64FBD45EE533BC394F728E57E23061E.gr7.us-east-1.eks.amazonaws.com
  k8sServicePort: 443
  ingressController:
    enabled: true
    loadbalancerMode: dedicated